#%RAML 0.8
title: hybris Products API
baseUri: http://localhost
version: v2
mediaType:  application/json

traits:
  - !include https://api.yaas.io/patterns/v1/trait-localized-modification.yaml
  - !include https://api.yaas.io/patterns/v1/trait-localized-retrieval.yaml
  - !include https://api.yaas.io/patterns/v2/trait-paged.yaml
  - !include https://api.yaas.io/patterns/v1/trait-sortable.yaml
  - !include https://api.yaas.io/patterns/v1/trait-queryable.yaml
  - !include https://api.yaas.io/patterns/v1/trait-yaas-aware.yaml
  - !include https://api.yaas.io/patterns/v1/trait-restricted.yaml
  - !include https://api.yaas.io/patterns/v1/trait-projectable.yaml


schemas:
  - ErrorMessage: !include https://api.yaas.io/patterns/v1/schema-error-message.json
  - MediaMetadata: !include schema/MediaMetadata.json
  - MediaMetadataCollection: !include schema/MediaMetadataCollection.json
  - MediaMetadataCreation: !include schema/MediaMetadataCreation.json
  - MediaMetadataUpdate: !include schema/MediaMetadataUpdate.json
  - ProductCreation: !include schema/ProductCreation.json
  - ProductUpdate: !include schema/ProductUpdate.json
  - Product: !include schema/Product.json
  - Products: !include schema/Products.json
  - ResourceLocation: !include schema/ResourceLocation.json
  - MediaLocation: !include schema/MediaLocation.json
  - TenantAction: !include schema/TenantAction.json
  - GenericResponse: !include schema/GenericResponse.json
  - ProductVariant: !include schema/ProductVariant.json
  - ProductVariants: !include schema/ProductVariants.json
  - ProductVariantCreation: !include schema/ProductVariantCreation.json

/{tenant}/products:
  get:
    is: [ localizedRetrieval, paged, sortable, queryable, yaasAware, projectable ]
    description: |
      Get all products.

      Accepted scopes:

        * `hybris.product_read_unpublished` - required to retrieve non-public products. If not provided only published products are returned

    headers:
      hybris-languages:
        default: false
    responses:
      200:
        description: |
          Resource successfully retrieved.
        headers:
          hybris-count:
            description: |
              Total count of queried elements.
            type: integer
            example: 100
        body:
          schema: Products
          example: !include schema/example/ProductsExample.json
      500:
        description: |
          Some server-side error occurred. Any details will be provided within the response payload.
        body:
          application/json:
            schema: ErrorMessage
      503:
        description: |
          Service temporarily unavailable.
        body:
          application/json:
            schema: ErrorMessage
  post:
    is: [ localizedModification, yaasAware, restricted ]
    description: |
      Create new product.

      Accepted scopes:

        * `hybris.product_create` - mandatory
        * `hybris.product_publish` - required if product is created as published (by providing published flag true )

    headers:
      Content-Language:
        description: |
          Single language code. If provided localized values should be provided as simple Strings, otherwise a 'language code/ value' map is expected for localized values.
    body:
      schema: ProductCreation
      example: !include schema/example/ProductCreationExample.json
    responses:
      201:
        description: |
          The resource has been successfully created.
        body:
          schema: ResourceLocation
        headers:
          Location:
            description : |
              The Location of the new resource which was created by the request.
              The value consists of a single absolute URI.
              example: http://www.hybris.com/items/myItem
              required : true
      404:
        description: |
          The requested resource does not exist.
        body:
          application/json:
            schema: ErrorMessage
      409:
         description: |
           Product with given code already exists.
         body:
           application/json:
             schema: ErrorMessage
      500:
        description: |
          Some server-side error occurred. Any details will be provided within the response payload.
        body:
          application/json:
            schema: ErrorMessage
      503:
        description: |
          Service temporarily unavailable.
        body:
          application/json:
            schema: ErrorMessage
  delete:
    is: [ yaasAware, restricted ]
    description: |
      Delete all Product entities.

      Accepted scopes:

      * `hybris.product_delete_all` - mandatory

    responses:
      204:
        description : |
          All products have been successfully deleted.
      500:
        description: |
          Some server-side error occurred. Any details will be provided within the response payload.
        body:
          application/json:
            schema: ErrorMessage
      503:
        description: |
          Service temporarily unavailable.
        body:
          application/json:
            schema: ErrorMessage
  /{productId}:
    get:
      is: [ localizedRetrieval, yaasAware, restricted, projectable ]
      description: |
        Retrieves a single product.

        Accepted scopes:

        * `hybris.product_read_unpublished` - required to retrieve non-public product
      responses:
        200:
          description: |
            Product successfully retrieved.
          body:
            schema: Product
            example: !include schema/example/ProductExample.json
        404:
          description: |
            The requested resource does not exist.
          body:
            application/json:
              schema: ErrorMessage
        500:
          description: |
            Some server-side error occurred. Any details will be provided within the response payload.
          body:
            application/json:
              schema: ErrorMessage
        503:
          description: |
            Service temporarily unavailable.
              body:
                application/json:
                  schema: ErrorMessage
    put:
      is: [ localizedModification, yaasAware, restricted ]
      description: |
        Update a single product.

        Accepted scopes:

        * `hybris.product_update` - required to update product data
        * `hybris.product_publish` - required to publish the product (by setting `published` flag to `true`)
        * `hybris.product_unpublish` - required to unpublish the product (by setting `published` flag to `false`)
      body:
        schema: ProductUpdate
        example: !include schema/example/ProductUpdateExample.json
      queryParameters:
        partial:
          description: |
            If true, a partial update will be supported, otherwise the full object replacement will be performed.
          type: boolean
          example: false
      headers:
        Content-Language:
          description: |
            Single language code. If provided localized values should be provided as simple Strings, otherwise a 'language code/ value' map is expected for localized values.
      responses:
        200:
          description: |
            The resource has been successfully updated.
          body:
            schema: GenericResponse
        400:
          description: |
            Request syntactically incorrect. Any details will be provided within the response payload.
        404:
          description: |
            The requested resource does not exist.
          body:
            application/json:
              schema: ErrorMessage
        409:
          description: |
            There are three possible reasons:
            1. Product with given code already exists, please choose unique code for your product
            2. Optimistic locking failed. If user sends metadata/version attribute which is outdated (someone else updated product in the time user was performing his changes). User should retrieve the latest product data and retry the request.
            3. Optimistic locking failed. User did not provide metadata/version attribute in update request, but someone else updated product while it was internally handled by product service. Resending the same request can result in successful update, but the update can override recently persisted changes.
          body:
            application/json:
              schema: ErrorMessage
        500:
          description: |
            Some server-side error occurred. Any details will be provided within the response payload.
          body:
            application/json:
              schema: ErrorMessage
        503:
          description: |
            Service temporarily unavailable.
          body:
            application/json:
              schema: ErrorMessage
    delete:
      is: [ yaasAware, restricted ]
      description: |
        Delete a single Product entity.

        Accepted scopes:

        * `hybris.product_delete` - mandatory

      responses:
        204:
          description : |
            The resource has been successfully deleted.
        404:
          description: |
            The requested resource does not exist.
          body:
            application/json:
              schema: ErrorMessage
        500:
          description: |
            Some server-side error occurred. Any details will be provided within the response payload.
          body:
            application/json:
              schema: ErrorMessage
        503:
          description: |
            Service temporarily unavailable.
          body:
            application/json:
              schema: ErrorMessage
    /media:
      description: |
        Media files of the product.
      post:
        is: [ yaasAware, restricted ]
        description: |
          Initialize process of creating new media file for product

          Accepted scopes:

          * `hybris.product_update` - mandatory
        body:
          application/json:
            schema: MediaMetadataCreation
            example: !include schema/example/MediaMetadataCreationExample.json
        responses:
          200:
            description:  |
              The process is successfully started.
            body:
              application/json:
                schema: MediaLocation
          404:
            description: |
              The requested resource does not exist.
            body:
              application/json:
                schema: ErrorMessage
          500:
            description: |
              Some server-side error occurred. Any details will be provided within the response payload.
            body:
              application/json:
                schema: ErrorMessage
          503:
            description: |
              Service temporarily unavailable.
            body:
              application/json:
                schema: ErrorMessage
      get:
        is: [ yaasAware, restricted ]
        description: |
          Return metadata of media files. The list is ordered according to the "position" attribute set in the file metadata.

          Accepted scopes:

          * `hybris.product_read_unpublished` - required to retrieve media metadata of non-public product
        responses:
          200:
            description: |
              Resource successfully retrieved.
            body:
              application/json:
                schema: MediaMetadataCollection
                example: !include schema/example/MediaMetadataCollectionExample.json
          404:
            description: |
              The requested resource does not exist.
            body:
              application/json:
                schema: ErrorMessage
          500:
            description: |
              Some server-side error occurred. Any details will be provided within the response payload.
            body:
              application/json:
                schema: ErrorMessage
          503:
            description: |
              Service temporarily unavailable.
            body:
              application/json:
                schema: ErrorMessage
      /{mediaId}:
        get:
          is: [ yaasAware, restricted ]
          description: |
            Return media file metadata by ID.

            Accepted scope:

            * `hybris.product_read_unpublished` - to retrieve media metadata of non-public product

          responses:
            200:
              description: |
                Resource successfully retrieved.
              body:
                application/json:
                  schema: MediaMetadata
                  example: !include schema/example/MediaMetadataExample.json
            404:
              description: |
                The requested resource does not exist.
              body:
                application/json:
                  schema: ErrorMessage
            500:
              description: |
                Some server-side error occurred. Any details will be provided within the response payload.
              body:
                application/json:
                  schema: ErrorMessage
            503:
              description: |
                Service temporarily unavailable.
              body:
                application/json:
                  schema: ErrorMessage
        put:
          is: [ yaasAware, restricted ]
          description: |
            Update media file metadata. Note that only part of the metadata field can be updated.

            Accepted scopes:

            * `hybris.product_update` - mandatory

          body:
            schema: MediaMetadataUpdate
            example: !include schema/example/MediaMetadataUpdateExample.json
          queryParameters:
            partial:
              description: |
                If true, a partial update will be supported, otherwise the full object replacement will be performed.
              type: boolean
              example: false
          responses:
            200:
              description: |
                The resource has been successfully updated.
              body:
                application/json:
                  schema: GenericResponse
            400:
              description: |
                Request syntactically incorrect. Any details will be provided within the response payload.
            404:
              description: |
                The requested resource does not exist.
              body:
                application/json:
                  schema: ErrorMessage
            409:
              description: |
                Optimistic locking failed. Someone else updated product with media while user request was internally handled by product service. Resending the same request can result in successful update, but the update can override recently persisted changes.
              body:
                application/json:
                  schema: ErrorMessage
            500:
              description: |
                Some server-side error occurred. Any details will be provided within the response payload.
              body:
                application/json:
                  schema: ErrorMessage
            503:
              description: |
                Service temporarily unavailable.
              body:
                application/json:
                  schema: ErrorMessage
        delete:
          is: [ yaasAware, restricted ]
          description: |
            Delete media identified by media ID.

            Accepted scopes:

            * `hybris.product_update` - mandatory

          responses:
            204:
              description: |
               The resource has been successfully deleted.
            404:
              description: |
                The requested resource does not exist.
              body:
                application/json:
                  schema: ErrorMessage
            500:
              description: |
                Some server-side error occurred. Any details will be provided within the response payload.
              body:
                application/json:
                  schema: ErrorMessage
            503:
              description: |
                Service temporarily unavailable.
              body:
                application/json:
                  schema: ErrorMessage
        /commit:
          post:
            is: [ yaasAware, restricted ]
            description: |
              Confirms that the media file specified by the media id is updated and ready to be used with product.

              Accepted scope:

              * `hybris.product_update` - required to attach media to product
            responses:
              202:
                description:  |
                  Request to attach media to product is accepted.
                body:
                  application/json:
                    schema: ResourceLocation
              404:
                description: |
                  The requested resource does not exist.
                body:
                  application/json:
                    schema: ErrorMessage
              409:
                description: |
                  Optimistic locking failed. Someone else updated product with media while user request was internally handled by product service. Resending the same request can result in successful update, but the update can override recently persisted changes.
                body:
                  application/json:
                    schema: ErrorMessage
              500:
                description: |
                  Some server-side error occurred. Any details will be provided within the response payload.
                body:
                  application/json:
                    schema: ErrorMessage
              503:
                description: |
                  Service temporarily unavailable.
                body:
                  application/json:
                    schema: ErrorMessage
    /variants:
      description: |
        Variants of the product.
      get:
        is: [localizedRetrieval, paged, sortable, queryable, yaasAware, projectable, restricted]
        description: |
            Get all variants.

            Accepted scopes:

              * `hybris.product_read_unpublished` - required to retrieve variants of non-public product. If not provided only variants of published product are returned
        responses:
          200:
            body:
              schema: ProductVariants
              example: !include schema/example/ProductVariantsExample.json
          404:
            description: |
              The requested resource does not exist.
            body:
              application/json:
                schema: ErrorMessage
          500:
            description: |
              Some server-side error occurred. Any details will be provided within the response payload.
            body:
              application/json:
                schema: ErrorMessage
          503:
            description: |
              Service temporarily unavailable.
            body:
              application/json:
                schema: ErrorMessage
      post:
        is: [localizedModification, restricted, yaasAware]
        description: |
          Create new product variant.

          Accepted scopes:

            * `hybris.product_create` - mandatory

        headers:
              Content-Language:
                description: |
                  Single language code. If provided localized values should be provided as simple Strings, otherwise a 'language code/value' map is expected for localized values.
        body:
          application/json:
            schema: ProductVariantCreation
            example: !include schema/example/ProductVariantCreationExample.json
        responses:
          201:
            description: |
              The resource has been successfully created.
            body:
              schema: ResourceLocation
            headers:
              Location:
                description : |
                  The Location of the new resource which was created by the request.
                  The value consists of a single absolute URI.
                example: http://www.hybris.com/items/myItem
                required : true
          404:
            description: |
              The requested resource does not exist.
            body:
              application/json:
                schema: ErrorMessage
          409:
            description: |
              Variant with given code already exists.
            body:
              application/json:
                schema: ErrorMessage
          500:
            description: |
              Some server-side error occurred. Any details will be provided within the response payload.
            body:
              application/json:
                schema: ErrorMessage
          503:
            description: |
              Service temporarily unavailable.
            body:
              application/json:
                schema: ErrorMessage

      delete:
        is: [ yaasAware, restricted ]
        description: |
          Delete all variants entities for specified product id.

          Accepted scopes:

          * `hybris.product_delete` - mandatory

        responses:
          204:
            description : |
              All products have been successfully deleted.
          500:
            description: |
              Some server-side error occurred. Any details will be provided within the response payload.
            body:
              application/json:
                schema: ErrorMessage
          503:
            description: |
              Service temporarily unavailable.
            body:
              application/json:
                schema: ErrorMessage
      /{variantId}:
        get:
          is: [localizedRetrieval, yaasAware, restricted]
          description: |
            Retrieve a single product variant.

            Accepted scopes:

            * `hybris.product_read_unpublished` - required to retrieve non-public product variants
          responses:
            200:
              body:
                schema: ProductVariant
                example: !include schema/example/ProductVariantExample.json
            404:
              description: |
                The requested resource does not exist.
              body:
                application/json:
                  schema: ErrorMessage
            500:
              description: |
                Some server-side error occurred. Any details will be provided within the response payload.
              body:
                application/json:
                  schema: ErrorMessage
            503:
              description: |
                Service temporarily unavailable.
              body:
                application/json:
                  schema: ErrorMessage
        put:
          is: [localizedModification, restricted, yaasAware]
          description: |
            Replace a single product variant.

            Accepted scopes:

            * `hybris.product_update` - required to update product data
            * `hybris.product_publish` - required to publish the product (by setting `published` flag to `true`)
            * `hybris.product_unpublish` - required to unpublish the product (by setting `published` flag to `false`)
          headers:
                  Content-Language:
                    description: |
                      Single language code. If provided localized values should be provided as simple Strings, otherwise a 'language code/ value' map is expected for localized values.
          body:
            application/json:
              schema: ProductVariantUpdate
              example: !include schema/example/ProductVariantUpdateExample.json
          responses:
            200:
              description: |
                The resource has been successfully updated.
              body:
                schema: GenericResponse
            400:
              description: |
                Request syntactically incorrect. Any details will be provided within the response payload.
            404:
              description: |
                The requested resource does not exist.
              body:
                application/json:
                  schema: ErrorMessage
            409:
              description: |
                Product with given sku already exists.
              body:
                application/json:
                  schema: ErrorMessage
            500:
              description: |
                Some server-side error occurred. Any details will be provided within the response payload.
              body:
                application/json:
                  schema: ErrorMessage
            503:
              description: |
                Service temporarily unavailable.
              body:
                application/json:
                  schema: ErrorMessage
        delete:
          is: [yaasAware, restricted]
          description: |
            Delete a single Product variant entity.

            Accepted scopes:

            * `hybris.product_delete` - mandatory
          responses:
            204:
              description : |
                The resource has been successfully deleted.
            404:
              description: |
                The requested resource does not exist.
              body:
                application/json:
                  schema: ErrorMessage
            500:
              description: |
                Some server-side error occurred. Any details will be provided within the response payload.
              body:
                application/json:
                  schema: ErrorMessage
            503:
              description: |
                Service temporarily unavailable.
              body:
                application/json:
                  schema: ErrorMessage
#        /media:
#          description: |
#            Media files of the product variant.
#          get:
#            is: [yaasAware, restricted]
#            description: |
#              Return metadata of media files. The list is ordered according to the "position" attribute set in the file metadata.
#
#              Accepted scopes:
#
#              * `hybris.product_read_unpublished` - required to retrieve non-public product variant media
#            responses:
#              200:
#                description: |
#                  Resource successfully retrieved.
#                body:
#                  application/json:
#                    schema: |
#                      {
#                         "$schema": "http://json-schema.org/draft-04/schema#",
#                         "type" : "array",
#                         "items": { "$ref": "MediaMetadata" }
#                      }
#                    example: !include schema/example/MediaMetadataCollectionExample.json
#              404:
#                description: |
#                  The requested resource does not exist.
#                body:
#                  application/json:
#                    schema: ErrorMessage
#              500:
#                description: |
#                  Some server-side error occurred. Any details will be provided within the response payload.
#                body:
#                  application/json:
#                    schema: ErrorMessage
#              503:
#                description: |
#                  Service temporarily unavailable.
#                body:
#                  application/json:
#                    schema: ErrorMessage
#          post:
#            is: [yaasAware, restricted]
#            description: |
#              Create a new media file. Use the application/json content type to create a file with an external URL and multipart/form-data.
#              to upload a file.
#
#              Accepted scopes:
#
#              * `hybris.product_update` - mandatory
#            body:
#              multipart/form-data:
#                formParameters:
#                  file:
#                    description: |
#                      Actual file content.
#                    required: true
#                    type: file
#                  metadata:
#                    description: |
#                      File meta-data as JSON object.
#                    example: !include schema/example/MediaMetadataCreationExample.json
#              application/json:
#                schema: ExternalMediaMetadataCreation
#                example: !include schema/example/ExternalMediaMetadataCreationExample.json
#            responses:
#              201:
#                description:  |
#                  The resource has been successfully created.
#                body:
#                  application/json:
#                    schema: ResourceLocation
#              404:
#                description: |
#                  The requested resource does not exist.
#                body:
#                  application/json:
#                    schema: ErrorMessage
#              500:
#                description: |
#                  Some server-side error occurred. Any details will be provided within the response payload.
#                body:
#                  application/json:
#                    schema: ErrorMessage
#              503:
#                description: |
#                  Service temporarily unavailable.
#                body:
#                  application/json:
#                    schema: ErrorMessage
#          /{mediaId}:
#            get:
#              is: [yaasAware, restricted]
#              description: |
#                Return media file metadata by ID.
#
#                Accepted scopes:
#
#                * `hybris.product_read_unpublished` - required to retrieve non-public product variant media
#              responses:
#                200:
#                  description: |
#                    Resource successfully retrieved.
#                  body:
#                    application/json:
#                      schema: MediaMetadata
#                      example: !include schema/example/MediaMetadataExample.json
#                404:
#                  description: |
#                    The requested resource does not exist.
#                  body:
#                    application/json:
#                      schema: ErrorMessage
#                500:
#                  description: |
#                    Some server-side error occurred. Any details will be provided within the response payload.
#                  body:
#                    application/json:
#                      schema: ErrorMessage
#                503:
#                  description: |
#                    Service temporarily unavailable.
#                  body:
#                    application/json:
#                      schema: ErrorMessage
#            put:
#              is: [ yaasAware, restricted ]
#              description: |
#                Update media file metadata. Note that only part of the metadata field can be updated.
#
#                Accepted scopes:
#
#                * `hybris.product_update` - mandatory
#
#              body:
#                schema: MediaMetadataUpdate
#              queryParameters:
#                partial:
#                  description: |
#                    If true, a partial update will be supported, otherwise the full object replacement will be performed.
#                  type: boolean
#                  example: false
#              responses:
#                200:
#                  description: |
#                    The resource has been successfully updated.
#                  body:
#                    application/json:
#                      schema: GenericResponse
#                400:
#                  description: |
#                    Request syntactically incorrect. Any details will be provided within the response payload.
#                404:
#                  description: |
#                    The requested resource does not exist.
#                  body:
#                    application/json:
#                      schema: ErrorMessage
#                500:
#                  description: |
#                    Some server-side error occurred. Any details will be provided within the response payload.
#                  body:
#                    application/json:
#                      schema: ErrorMessage
#                503:
#                  description: |
#                    Service temporarily unavailable.
#                  body:
#                    application/json:
#                      schema: ErrorMessage
#            delete:
#              is: [ yaasAware, restricted ]
#              description: |
#                Delete media identified by media ID.
#
#                Accepted scopes:
#
#                * `hybris.product_update` - mandatory
#
#              responses:
#                204:
#                  description: |
#                   The resource has been successfully deleted.
#                404:
#                  description: |
#                    The requested resource does not exist.
#                  body:
#                    application/json:
#                      schema: ErrorMessage
#                500:
#                  description: |
#                    Some server-side error occurred. Any details will be provided within the response payload.
#                  body:
#                    application/json:
#                      schema: ErrorMessage
#                503:
#                  description: |
#                    Service temporarily unavailable.
#                  body:
#                    application/json:
#                      schema: ErrorMessage
#            /content:
#              get:
#                is: [ yaasAware, restricted ]
#                description: |
#                  Returns redirection to URL with media content for a given media ID.
#
#                  Accepted scope:
#
#                  * `hybris.product_read_unpublished` - required to retrieve media content of non-public product
#                responses:
#                  301:
#                    headers:
#                      Location:
#                        description : |
#                          The Location of the new resource which was created by the request.
#                          The value consists of a single absolute URI.
#                          example: http://www.hybris.com/items/myItem
#                  404:
#                    description: |
#                      The requested resource does not exist.
#                    body:
#                      application/json:
#                        schema: ErrorMessage
#                  503:
#                    description: |
#                      Service temporarily unavailable.
#                    body:
#                      application/json:
#                        schema: ErrorMessage
